eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8863
spring:
  application:
    name: service-feign
#默认未打开hystrix断路器
feign:
  hystrix:
    enabled: true

