version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: c-nginx
    volumes:
      - ./nginx/www/:/usr/share/nginx/html
      #- ./nginx/conf.d/app.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
    networks:
      - cui-ci
  redis:
    image: redis:latest
    container_name: c-redis
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - cui-ci
  mysql:
    container_name: c-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - cui-ci
    restart: always
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: c-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - cui-ci
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  zookeeper:
    image: zookeeper:latest
    container_name: c-zookeeper
    networks:
      - cui-ci
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper:/conf/
    restart: always
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: c-zipkin
    networks:
      - cui-ci
    ports:
      - 9411:9411
    restart: always
  xxljob:
    image: 39.100.194.142:5000/cui/xxljob:latest
    container_name: c-xxljob
    depends_on:
      - mysql
    volumes:
      - ./xxljob/applogs:/data/applogs
    ports:
      - "19999:19999"
    environment:
      TZ: Asia/Shanghai
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?characterEncoding=utf8&amp;useSSL=false --spring.datasource.username=root --spring.datasource.password=root --xxl.job.login.username=admin --xxl.job.login.password=123456'
    networks:
      - cui-ci
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  dubbo-admin:
    image: 39.100.194.142:5000/cui/dubbo-admin:latest
    container_name: c-dubbo-admin
    networks:
      - cui-ci
    links:
      - zookeeper:zookeeper
    depends_on:
      - zookeeper
    ports:
      - 18888:18888
    restart: always
  chaos-admin:
    image: 39.100.194.142:5000/cui/chaos-admin:latest
    container_name: c-chaos-admin
    networks:
      - cui-ci
    ports:
      - 8000:8000
    restart: always
networks:
  cui-ci:
    driver: bridge
