version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: c-nginx
    volumes:
      - ./nginx/www/:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    restart: always
    networks:
      - cui-ci
  redis:
    image: redis:latest
    container_name: c-redis
    restart: always
    command: redis-server --requirepass Sike2018Okya2020!
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - cui-ci
  mysql:
    container_name: c-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Sike2018Okya2020!
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - cui-ci
    restart: always
  zookeeper:
    image: zookeeper:latest
    container_name: c-zookeeper
    networks:
      - cui-ci
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper:/conf/
    restart: always
networks:
  cui-ci:
    driver: bridge
