server:
  port: 8888
spring:
  application:
    name: service.gateway
  profiles:
    active: after_route
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: server-user
          uri: lb://SERVER-USER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://peer1:18761/eureka/,http://peer2:28761/eureka/
---
spring:
  profiles: after_route
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2019-01-20T17:42:47.789-07:00[America/Denver]

